CREATE TABLE comments (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    Message TEXT NOT NULL,
    UserId UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    BookId UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(UserId, BookId)
);