CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Username VARCHAR(255) NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
