CREATE TABLE tokens (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    Token TEXT NOT NULL,
    UserId UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ExpiresAt TIMESTAMP (3),
    CreatedAt TIMESTAMP (3) DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE tokens ADD COLUMN token TEXT NOT NULL;