CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    Username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    Avatar TEXT NOT NULL,
    CreatedAt TIMESTAMP (3) DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP (3) DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE users ADD COLUMN avatar TEXT NOT NULL;
